# Generated by Django 3.1.3 on 2021-02-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, default='/no_image.png', null=True, upload_to='images/%Y/%M/', verbose_name='Малюнок або фото:')),
                ('body', models.TextField(blank=True, null=True, verbose_name="Опис (не обов'язково):")),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, verbose_name='Slug (не заповнювати): ')),
                ('tags', models.ManyToManyField(null=True, to='gallery.Tag', verbose_name='Теги:')),
            ],
        ),
    ]
